package com.tactilelens.app.inference

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.util.Log
import org.tensorflow.lite.Interpreter
import org.tensorflow.lite.support.common.FileUtil
import org.tensorflow.lite.support.common.ops.NormalizeOp
import org.tensorflow.lite.support.image.ImageProcessor
import org.tensorflow.lite.support.image.TensorImage
import org.tensorflow.lite.support.image.ops.ResizeOp
import java.nio.FloatBuffer

/**
 * Handles Stage 0: Background Removal using the custom U2Net LiteRT model.
 * Replaces Google ML Kit with a direct Neural Network NPU inference.
 */
class SegmentationHelper(private val context: Context) {
    
    private var interpreter: Interpreter? = null
    
    // U2Net typically expects 320x320 input
    private val modelInputSize = 320
    
    private val imageProcessor = ImageProcessor.Builder()
        .add(ResizeOp(modelInputSize, modelInputSize, ResizeOp.ResizeMethod.BILINEAR))
        .add(NormalizeOp(127.5f, 127.5f)) // Assuming standard normalization
        .build()

    init {
        setupLiteRT()
    }

    private fun setupLiteRT() {
        try {
            // Load the optimized U2Net model generated by AI Hub
            val modelBuffer = FileUtil.loadMappedFile(context, "u2net_optimized.tflite")

            // Route to Hexagon NPU
            val options = Interpreter.Options().apply {
                useNNAPI = true 
                numThreads = 4 
            }

            interpreter = Interpreter(modelBuffer, options)
            Log.i("SegmentationHelper", "U2Net Interpreter initialized with NNAPI (NPU).")

        } catch (e: Exception) {
            Log.e("SegmentationHelper", "Failed to initialize U2Net: ${e.message}")
        }
    }

    data class SegmentationResult(val croppedBitmap: Bitmap, val maskBitmap: Bitmap)

    /**
     * Segments the input frame and returns both the foreground object and the B/W mask.
     */
    fun segmentForeground(bitmap: Bitmap, onResult: (SegmentationResult?) -> Unit) {
        if (interpreter == null) {
            Log.e("SegmentationHelper", "Interpreter not initialized. Returning null.")
            onResult(null)
            return
        }

        try {
            // 1. Preprocess the image for U2Net
            val tensorImage = imageProcessor.process(TensorImage.fromBitmap(bitmap))
            
            // 2. Prepare output buffer
            val outputTensor = interpreter!!.getOutputTensor(0)
            val shape = outputTensor.shape()
            // NCHW is [1, 1, 320, 320], NHWC is [1, 320, 320, 1]. Grab the actual spatial dimensions.
            val maskH = if (shape[1] > 1) shape[1] else shape[2]
            val maskW = if (shape[1] > 1) shape[2] else shape[3]
            
            val outputBuffer = FloatBuffer.allocate(maskH * maskW)

            // 3. Run Inference on NPU
            interpreter!!.run(tensorImage.tensorBuffer.buffer, outputBuffer)

            // 4. Post-process: Apply the mask back to the original bitmap
            outputBuffer.rewind()
            val result = applyMask(bitmap, outputBuffer, maskW, maskH)
            
            onResult(result)

        } catch (e: Exception) {
            Log.e("SegmentationHelper", "U2Net segmentation failed: ${e.message}")
            onResult(null) 
        }
    }

    private fun applyMask(original: Bitmap, maskBuffer: FloatBuffer, maskW: Int, maskH: Int): SegmentationResult {
        // Create a scaled down version of the original to match mask dimensions
        val scaledOriginal = Bitmap.createScaledBitmap(original, maskW, maskH, true)
        val maskedBitmap = Bitmap.createBitmap(maskW, maskH, Bitmap.Config.ARGB_8888)
        val bwMaskBitmap = Bitmap.createBitmap(maskW, maskH, Bitmap.Config.ARGB_8888)
        
        // Very basic mask application: if mask value > threshold, keep pixel, else transparent
        for (y in 0 until maskH) {
            for (x in 0 until maskW) {
                val maskValue = maskBuffer.get(y * maskW + x)
                
                // Grayscale pixel for mask
                val intensity = (maskValue.coerceIn(0f, 1f) * 255).toInt()
                val maskColor = Color.argb(255, intensity, intensity, intensity)
                bwMaskBitmap.setPixel(x, y, maskColor)

                if (maskValue > 0.5f) { // Threshold
                    maskedBitmap.setPixel(x, y, scaledOriginal.getPixel(x, y))
                } else {
                    maskedBitmap.setPixel(x, y, Color.TRANSPARENT)
                }
            }
        }
        
        // Scale it back to original size for the next stage
        val finalMasked = Bitmap.createScaledBitmap(maskedBitmap, original.width, original.height, true)
        val finalBwMask = Bitmap.createScaledBitmap(bwMaskBitmap, original.width, original.height, true)
        return SegmentationResult(finalMasked, finalBwMask)
    }

    fun close() {
        interpreter?.close()
        interpreter = null
    }
}
