package com.example.tactilelens.inference

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.util.Log
import org.tensorflow.lite.Interpreter
import org.tensorflow.lite.support.common.FileUtil
import org.tensorflow.lite.support.common.ops.NormalizeOp
import org.tensorflow.lite.support.image.ImageProcessor
import org.tensorflow.lite.support.image.TensorImage
import org.tensorflow.lite.support.image.ops.ResizeOp
import java.nio.FloatBuffer

/**
 * Handles Stage 0: Background Removal using the custom U2Net LiteRT model.
 * Replaces Google ML Kit with a direct Neural Network NPU inference.
 */
class SegmentationHelper(private val context: Context) {
    
    private var interpreter: Interpreter? = null
    
    // U2Net typically expects 320x320 input
    private val modelInputSize = 320
    
    private val imageProcessor = ImageProcessor.Builder()
        .add(ResizeOp(modelInputSize, modelInputSize, ResizeOp.ResizeMethod.BILINEAR))
        // ImageNet mean/std × 255 — must match U2Net training preprocessing
        .add(NormalizeOp(
            floatArrayOf(123.675f, 116.28f, 103.53f),
            floatArrayOf(58.395f, 57.12f, 57.375f)
        ))
        .build()

    init {
        setupLiteRT()
    }

    private fun setupLiteRT() {
        try {
            // Load the optimized U2Net model generated by AI Hub
            val modelBuffer = FileUtil.loadMappedFile(context, "u2net_small.tflite")

            // Route to Hexagon NPU
            val options = Interpreter.Options().apply {
                useNNAPI = true 
                numThreads = 4 
            }

            interpreter = Interpreter(modelBuffer, options)
            Log.i("SegmentationHelper", "U2Net Interpreter initialized with NNAPI (NPU).")

        } catch (e: Exception) {
            Log.e("SegmentationHelper", "Failed to initialize U2Net: ${e.message}")
        }
    }

    /**
     * Segments the input frame and returns a Bitmap containing ONLY the foreground object.
     */
    fun segmentForeground(bitmap: Bitmap, onResult: (Bitmap?) -> Unit) {
        if (interpreter == null) {
            Log.e("SegmentationHelper", "Interpreter not initialized. Returning original.")
            onResult(bitmap)
            return
        }

        try {
            // 1. Preprocess the image for U2Net
            val tensorImage = imageProcessor.process(TensorImage.fromBitmap(bitmap))
            
            // 2. Prepare output buffer (U2Net outputs a 1-channel alpha mask, e.g. 1x320x320x1)
            val outputTensor = interpreter!!.getOutputTensor(0)
            val (_, h, w, c) = outputTensor.shape()
            val outputBuffer = FloatBuffer.allocate(h * w * c)

            // 3. Run Inference on NPU
            interpreter!!.run(tensorImage.tensorBuffer.buffer, outputBuffer)

            // 4. Post-process: Apply the mask back to the original bitmap
            outputBuffer.rewind()
            val maskedBitmap = applyMask(bitmap, outputBuffer, w, h)
            
            onResult(maskedBitmap)

        } catch (e: Exception) {
            Log.e("SegmentationHelper", "U2Net segmentation failed: ${e.message}")
            onResult(bitmap) 
        }
    }

    private fun applyMask(original: Bitmap, maskBuffer: FloatBuffer, maskW: Int, maskH: Int): Bitmap {
        // Create a scaled down version of the original to match mask dimensions
        val scaledOriginal = Bitmap.createScaledBitmap(original, maskW, maskH, true)
        val maskedBitmap = Bitmap.createBitmap(maskW, maskH, Bitmap.Config.ARGB_8888)
        
        // Very basic mask application: if mask value > threshold, keep pixel, else transparent
        for (y in 0 until maskH) {
            for (x in 0 until maskW) {
                val maskValue = maskBuffer.get(y * maskW + x)
                if (maskValue > 0.5f) { // Threshold
                    maskedBitmap.setPixel(x, y, scaledOriginal.getPixel(x, y))
                } else {
                    maskedBitmap.setPixel(x, y, Color.TRANSPARENT)
                }
            }
        }
        
        // Scale it back to original size for the next stage (MobileNet)
        return Bitmap.createScaledBitmap(maskedBitmap, original.width, original.height, true)
    }

    fun close() {
        interpreter?.close()
        interpreter = null
    }
}
